#!/usr/bin/env python

# Author: Eric Kow
# License: BSD3

"""
Example script using the library to dump the contents of a single glozz file
"""

import educe.glozz      as educe
import os.path
import sys

# ---------------------------------------------------------------------
# example
# ---------------------------------------------------------------------

default_file='example.aa'

if len(sys.argv) > 1:
   files=sys.argv[1:]
elif os.path.isfile(default_file):
   files=[default_file]
else:
   print >> sys.stderr ("Usage: %s glozz-file [glozz-file..]" % sys.argv[0])


def dump(filename, doc):
    show_unit = lambda u:"%s | %s" % (u, doc.text(u))
    lines = ['############### %s units' % filename]\
          + map(show_unit, annotations.units)\
          + ['############### %s relations' % filename]\
          + map(str, annotations.rels)
    return "\n".join(lines)

for file in files:
    fbase,fext = os.path.splitext(file)
    if fext is None:
        ac_file = None
    else:
        ac_file = fbase + ".ac"
    annotations = educe.read_annotation_file(file,ac_file)
    print dump(file, annotations)
    print ""

# vim: syntax=python:
