#!/usr/bin/env python
# -*- coding: utf-8 -*-

# pylint: disable=invalid-name
# We have a script here, not a module, so it's ok to have
# a funny name
# pylint: enable=invalid-name

# Author: Eric Kow
# License: CeCILL (French BSD3-like)

"""
RST_DT Swiss-Army knife
"""

import argparse

from educe.rst_dt.util.cmd import SUBCOMMANDS
from educe.util import add_subcommand

def main():
    "rst-util main"

    arg_parser = argparse.ArgumentParser(description='RST-DT Swiss Army Knife')
    subparsers = arg_parser.add_subparsers(help='sub-command help')

    for module in SUBCOMMANDS:
        subparser = add_subcommand(subparsers, module)
        module.config_argparser(subparser)

    arg_parser.add_argument('--verbose', '-v',
                            action='count',
                            default=0)
    args = arg_parser.parse_args()
    args.func(args)

main()
