#!/usr/bin/env python
# -*- coding: utf-8 -*-

# pylint: disable=invalid-name
# We have a script here, not a module, so it's ok to have
# a funny name
# pylint: enable=invalid-name

# Author: Eric Kow
# License: CeCILL (French BSD3-like)

"""
RST-DT project tools for learning on our data
"""

import argparse

from educe.rst_dt.learning.cmd import SUBCOMMANDS


def main():
    "rst-dt-learning main"

    arg_parser = argparse.ArgumentParser(description='RST DT learning kit')
    subparsers = arg_parser.add_subparsers(help='sub-command help')

    for module in SUBCOMMANDS:
        subparser = subparsers.add_parser(module.NAME,
                                          help=module.__doc__)
        module.config_argparser(subparser)

    arg_parser.add_argument('--verbose', '-v',
                            action='count',
                            default=0)
    args = arg_parser.parse_args()
    args.func(args)

main()
