#!/usr/bin/env python
# -*- coding: utf-8 -*-

# pylint: disable=invalid-name
# We have a script here, not a module, so it's ok to have
# a funny name
# pylint: enable=invalid-name

# Author: Eric Kow
# License: CeCILL (French BSD3-like)

"""
STAC project corpus sanity checker
"""

from educe.stac.sanity.main import main

main()
