#!/usr/bin/env python
# -*- coding: utf-8 -*-

# pylint: disable=invalid-name
# We have a script here, not a module, so it's ok to have
# a funny name
# pylint: enable=invalid-name

# Author: Eric Kow
# License: CeCILL (French BSD3-like)

"""
STAC project Swiss-Army knife
"""

from argparse import ArgumentParser

from educe.stac.util.cmd import SUBCOMMANDS


def main():
    "stac-util main"

    psr = ArgumentParser(description='STAC Swiss Army Knife')
    subparsers = psr.add_subparsers(help='sub-command help')

    for module in SUBCOMMANDS:
        module_help_parts = [x for x in module.__doc__.strip().split('\n', 1)
                             if x]
        if len(module_help_parts) > 1:
            module_help = module_help_parts[0]
            module_epilog = '\n'.join(module_help_parts[1:]).strip()
        else:
            module_help = module.__doc__
            module_epilog = None
        subparser = subparsers.add_parser(module.NAME,
                                          help=module_help,
                                          epilog=module_epilog)
        module.config_argparser(subparser)

    psr.add_argument('--verbose', '-v',
                     action='count',
                     default=0)
    args = psr.parse_args()
    args.func(args)

main()
