#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Author: Eric Kow
# License: CeCILL (French BSD3-like)

"""
STAC project tools for learning on our data
"""

import argparse

from educe.stac.learning.cmd import SUBCOMMANDS
from educe.util import add_subcommand


def main():
    "stac-learning main"

    arg_parser = argparse.ArgumentParser(description='STAC learning kit')
    subparsers = arg_parser.add_subparsers(help='sub-command help')

    for module in SUBCOMMANDS:
        subparser = add_subcommand(subparsers, module)
        module.config_argparser(subparser)

    arg_parser.add_argument('--verbose', '-v',
                            action='count',
                            default=0)
    args = arg_parser.parse_args()
    args.func(args)

main()
